{
    'name': 'Asset & Resource Management',
    'version': '19.0.1.0.0',
    'category': 'Inventory/Inventory',
    'summary': 'Internal Asset & Resource Management System',
    'description': """
        Manage company assets, allocations, transfers, resource bookings,
        maintenance requests, and audits with role-based access control.
    """,
    'author': 'AssetFlow',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/sequence_data.xml',
        'data/cron_data.xml',
        'data/mail_activity_data.xml',
        'views/base_setup_views.xml',
        'views/asset_views.xml',
        'views/allocation_views.xml',
        'views/booking_views.xml',
        'views/audit_views.xml',
        'views/dashboard.xml',
        'views/report_views.xml',
        'views/log_views.xml',
        'views/transfer_views.xml',
        'views/maintenance_views.xml',
        'views/menus.xml',
        'wizard/return_condition_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'asset_management/static/src/js/dashboard.js',
            'asset_management/static/src/xml/dashboard.xml',
            'asset_management/static/src/css/dashboard.css',
            'asset_management/static/src/js/kanban_widget.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
